dist: trusty
sudo: false
conditions: v1
git:
  depth: 2
language: node_js
node_js: 8
cache: yarn
script:
- node_modules/.bin/gulp lint
jobs:
  include:
  - stage: release
    if: |
      branch = master AND \
      fork = false AND \
      commit_message !~ /^Release / AND \
      commit_message !~ / \[skip release\]$/
    deploy:
    - provider: script
      skip_cleanup: true
      script: node_modules/.bin/gulp release
