= Asciidoctor Docs UI
// Variables:
:current-release: v3
// Settings:
:experimental:
:hide-uri-scheme:
:toc: macro
ifdef::env-github[]
:important-caption: :exclamation:
:!toc-title:
:badges:
endif::[]
// Project URLs:
:project-repo-name: asciidoctor/docs.asciidoctor.org-ui
:url-project: https://github.com/{project-repo-name}
:url-preview: https://asciidoctor-docs-ui.netlify.com
:url-ci: https://travis-ci.org/asciidoctor/docs.asciidoctor.org-ui
// External URLs:
:url-antora: https://antora.org
:url-asciidoctor: https://asciidoctor.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-opendevise: https://opendevise.com
:url-node: https://nodejs.org
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation
:url-yarn: https://yarnpkg.com

ifdef::badges[]
image:https://img.shields.io/github/release/{project-repo-name}.svg[Latest Release,link={url-project}/releases/download/{current-release}/ui-bundle.zip]
endif::[]

toc::[]

This project provides the UI for the Asciidoctor docs site.
The UI bundle that this project produces is designed to be used with Antora.
It contains the HTML templates (layouts, partials, and helpers), CSS, JavaScript, fonts, and site-wide images.
As such, it provides both the visual theme and user interactions for the docs site.
The rest of the material for the docs site comes from the content repositories.

== Usage

To use this UI with Antora, add the following configuration to the playbook file for your site:

[source,yaml,subs=attributes+]
----
ui:
  bundle:
    url: {url-project}/releases/download/{current-release}/ui-bundle.zip
----

Read on to learn how to develop the UI.

== Development Quickstart

This section offers a basic tutorial to learn how to set up the UI project, preview it locally, and bundle it for use with Antora.

=== Prerequisites

To preview and bundle the UI, you need the following software on your computer:

* {url-git}[git] (command: `git`)
* {url-node}[Node 8] (command: `node`)
* {url-gulp}[Gulp CLI] (command: `gulp`)
* {url-yarn}[Yarn] (command: `yarn`)

==== git

First, make sure you have git installed.

 $ git --version

If not, {url-git-dl}[download and install] the git package for your system.

==== Node 8

Next, make sure that you have Node 8 installed.

 $ node -v

If this command fails with an error, you don't have Node installed.
If the command doesn't report a Node 8 version (e.g., v8.12.0), then you don't have a suitable version of Node installed.

While you can install Node from the official packages, we strongly recommend that you use {url-nvm}[nvm] (Node Version Manager) to install and manage Node.
Follow the {url-nvm-install}[nvm installation instructions] to set up nvm on your machine.

Once you've installed nvm, open a new terminal and install Node 8 using the following command:

 $ nvm install 8

You can switch to this version of Node at any time using the following command:

 $ nvm use 8

To make Node 8 the default in new terminals, type:

 $ nvm alias default 8

Now that you have Node 8 installed, you can proceed with installing Yarn and the Gulp CLI.

==== Yarn

Next, you'll need Yarn, which is the preferred package manager for the Node ecosystem.

You should install Yarn globally (which resolves to a location in your user directory if you're using nvm) using the following command:

 $ npm install -g yarn

Verify Yarn is installed and on your PATH by running:

 $ yarn -v

==== Gulp CLI

Finally, you'll need the Gulp command-line interface (CLI).
This package provides the `gulp` command which executes the version of Gulp declared by the project.

You should install the Gulp CLI globally (which resolves to a location in your user directory if you're using nvm) using the following command:

 $ npm install -g gulp-cli

If you prefer to install global packages using Yarn, run this command instead:

 $ yarn global add gulp-cli

Verify the Gulp CLI is installed and on your PATH by running:

 $ gulp -v

Now that you have the prerequisites installed, you can fetch and build the UI project.

=== Clone and Initialize the UI Project

Clone the UI project using git:

[subs=attributes+]
 $ git clone {url-project} docs-ui &&
   cd docs-ui

The example above clones the Couchbase docs UI project and then switches to the project folder on your filesystem.
Stay in this project folder when executing all subsequent commands.

Use Yarn to install the project's dependencies inside the project.
In your terminal, execute the following command:

 $ yarn install

This command installs the dependencies listed in [.path]_package.json_ into the [.path]_node_modules/_ folder inside the project.
This folder does not get included in the UI bundle and should _not_ be committed to the source control repository.

=== Preview the UI

The UI project is configured to preview offline.
The files in the [.path]_preview-site-src/_ folder provide the sample content that allow you to see the UI in action.
In this folder, you'll primarily find pages written in AsciiDoc.
These pages provide a representative sample and kitchen sink of content from the real site.

To build the UI and preview it in a local web server, run the `preview` command:

 $ gulp preview

You'll see a URL listed in the output of this command:

....
[18:24:29] Server started http://localhost:5252
[18:24:29] Running server
....

Navigate to this URL to preview the site locally.

While this command is running, any changes you make to the source files will be instantly reflected in the browser.
This works by monitoring the project for changes, running the `build` task if a change is detected, and sending the updates to the browser.

Press kbd:[Ctrl+C] to stop the preview server and end the continuous build.

=== Online Preview

You can share a preview of the UI online by submitting a pull request to GitHub.
The repository is configured to create a deploy preview on Netlify for every pull request.
Here's how that process works:

. Fork the repository on GitHub (only has to be done once).
. Create a local branch.
. Make changes to the UI.
. Commit your changes to that branch.
. Push that branch to your fork (on GitHub).
. Submit a pull request from the branch you pushed to your fork.
. Wait for deploy/netlify check to say "`Deploy preview ready`" on the pull request page.
. Click on the "`Details`" link under "`Show all checks`" on the pull request page.
. View your changes in the deploy preview or share the preview URL with others.

The deploy preview works because there is a webhook on the repository that pings \https://api.netlify.com/hooks/github for the following events: push, pull_request, delete_branch.
Netlify then runs the command specified in netlify.toml, deploys the site, and allocates a temporary preview URL for it.

Included in that temporary preview URL is the UI bundle itself.
That means you can test it directly with Antora.
Simply append `dist/ui-bundle.zip` to the end of the preview URL and pass it to Antora as follows:

 $ antora --ui-bundle-url=<preview URL>/dist/ui-bundle.zip antora-playbook.yml

The temporary preview URL will automatically be decommissioned once the PR is closed.

=== Package for Use with Antora

If you need to package the UI so you can use it to generate the docs site locally, run the following command:

 $ gulp pack

If any errors are reported by lint, you'll need to fix them.

When the command completes successfully, the UI bundle will be available at [.path]_build/ui-bundle.zip_.
You can point Antora at this bundle using the `--ui-bundle-url` command-line option (e.g., `--ui-bundle-url=../docs-ui/build/ui-bundle.zip`).

== Releases

Releases are handled by the `gulp release` task, which is automated by a CI job.
The release process boils down to the following steps:

. Pack the UI bundle.
. Tag the git repository using the next version number in the sequence (e.g., v100 after v99)
. Create a GitHub release from that git tag.
. Attach the UI bundle to that release as an asset in zip format.
. Update the README to reference the URL of the lastest bundle and commit that update to the repository.

Fortunately, you don't have to do any of these steps yourself.
These steps are fully automated by the `gulp release` task.
In fact, you don't even have to run this task.
Whenever a commit is pushed to the master branch of the repository, it triggers the CI job on master, which executes the `gulp release` task using pre-configured credentials.

IMPORTANT: A release will only be made if the project validates (i.e., all lint tasks pass).
To validate the project, run `gulp lint` before pushing your changes to GitHub.

The CI job is already configured, so there's nothing you need to do to make automated release work.
All you have to do is commit your changes and push those commits to the master branch of the git repository.
A few seconds later, a new bundle will be available for use with Antora.
Run `git pull` to retrieve the updated README that includes the new URL.

If you want to commit a change to master without making a release, add the string `[skip ci]` to the end of the commit message.

The next two sections document how the CI job is set up an configured.

=== Release Task Prerequisites

In addition to the <<Prerequisites>> covered above, you'll need a personal access token for the automated GitHub account, asciidoctor-docbot, so it has permission to make changes to the repository on GitHub.
The asciidoctor-docbot account will need at least write access to the {url-project} repository, though admin access is recommended.

Start by creating a https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/[personal access token] for the asciidoctor-docbot user.
The `release` task relies on this token to interact with the GitHub API to create the tag, create the release, and attach the UI bundle.
The token must have the `public_repo` scope.
No other scopes are required (as long as the asciidoctor-docbot user has write access to the repository).

=== CI Job

The {url-ci}[CI job] is executed on Travis CI and is defined in the file [.path]_.travis.yml_.
It boils down to running the `gulp release` task on the master branch.
The GITHUB_TOKEN environment variable is defined in the job configuration.

Once the CI job runs and a new UI bundle is available, you can update the URL of the UI bundle in the Antora playbook file.
See <<Usage>> for details.

== Copyright and License

=== Software

The software in this repository (Gulp build script and tasks, web JavaScript files, Handlebars templates, common CSS, utility icons, etc.) is part of the {url-antora}[Antora project].
As such, use of the software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

=== Branding and Design

Copyright (C) {url-asciidoctor}[Asciidoctor] 2018.
This includes any CSS that provides colors or iconography that depict the Asciidoctor brand.
All rights reserved (until further notice).
