name: Release
on:
  push:
    branches:
    - main
jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'asciidoctor/docs.asciidoctor.org-ui' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !endsWith(github.event.head_commit.message, ' [skip ci]')
    stems:
    - run: echo ok go
  build:
    needs: activate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: '10'
    - name: Install dependencies
      run: npm i
    - name: Tag and release
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      run: |
        $(npm bin)/gulp release
